name: ReactSurgeExample
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.Js Environment
        uses: actions/setup-node@v2-beta
        with:
          version: 12

      - name: Setup Yarn Environment
        uses: Borales/actions-yarn@v2.1.0
        with:
            # Yarn command
            cmd: install  # Yarn Install/ npm Install
      
        - name: creating build
          run: sudo yarn build
        
      - name: Installing Surge
        run: npm install -global surge
      
      - name: Deploying On Surge
        run: surge ./build http://alcoholic-curve.surge.sh/ --token ${{secrets.SURGE_TOKEN}}